### ISSUE TITLE
I can see this issue when invoking lambda function locally. Invalid time zone specified

### ISSUE THREAD

**Issue by blkdot** [castleadmin/nx-plugins#10]
{"errorType": "RangeError", "errorMessage": "Invalid time zone specified: :/etc/localtime", "trace": ["RangeError: Invalid time zone specified: :/etc/localtime", "    at new DateTimeFormat (<anonymous>)", "    at #getDateFormatter (file:///var/task/index.mjs:1101:12)", "    at #generateISOTimestampWithOffset (file:///var/task/index.mjs:1119:78)", "    at PowertoolsLogFormatter.formatTimestamp (file:///var/task/index.mjs:1070:50)", "    at PowertoolsLogFormatter.formatAttributes (file:///var/task/index.mjs:1185:23)", "    at _Logger.createAndPopulateLogItem (file:///var/task/index.mjs:1790:35)", "    at _Logger.processLogItem (file:///var/task/index.mjs:1891:38)", "    at _Logger.info (file:///var/task/index.mjs:1458:10)", "    at Runtime.exampleHandler [as handler] (file:///var/task/index.mjs:2080:10)", "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"]}

**Comment by blkdot** [comment]
Got it. thanks for your kind explanation.
